// This file is now obsolete. MySQL is used for all database operations.

// Please refer to the migration documentation for further details.
// sql.worker.ts - runs sql.js in a dedicated classic web worker
// Requires /public/sql-wasm.js (UMD build) and /public/sql-wasm.wasm

declare const initSqlJs: any;
declare function importScripts(url: string): void;

console.log('sql.worker.ts: Worker started');

// Load sql.js UMD build
importScripts('/sql-wasm.js');

let SQL: any = null;
let db: any = null;

// Ensure hard-coded admin account exists
function ensureAdminAccount() {
  try {
    const adminEmail = 'admin@admin.local';
    const adminUser = db.exec(`SELECT * FROM users WHERE email = '${adminEmail}'`);
    console.log('[sql.worker.ts] Admin check query result:', adminUser);
    if (!adminUser || !adminUser[0] || adminUser[0].values.length === 0) {
      console.log('[sql.worker.ts] No admin found, attempting to insert hard-coded admin...');
      // Precomputed hash/salt for password 'admin123' using PBKDF2, 150000 iterations, 16-byte salt, SHA-256
      // Generated by generate-admin-hash.js
      const salt = 'a4zfH3hpiF58dOUhMUMAAw==';
      const hash = 'M0iq+elJ7kD1Sk2ExAN/Yhnyg1XM0fwzz8K186nPysc=';
      const now = new Date().toISOString();
      try {
        db.run(`INSERT INTO users (id, email, displayName, passwordHash, passwordSalt, isAdmin, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, [
          'admin-hardcoded',
          adminEmail,
          'admin',
          hash,
          salt,
          1,
          now,
          now
        ]);
        console.log('[sql.worker.ts] Hard-coded admin account created');
      } catch (insertErr) {
        console.error('[sql.worker.ts] Error during admin insert:', insertErr);
      }
    } else {
      console.log('[sql.worker.ts] Admin already exists, not inserting.');
    }
  } catch (e) {
    console.error('[sql.worker.ts] Failed to check/insert hard-coded admin', e);
  }
}

// Migration function to ensure all tables exist
function runMigrations() {
  console.log('sql.worker.ts: Running migrations...');
  
  // Ensure admin_requests table exists
  try {
    const adminTableResult = db.exec(`SELECT name FROM sqlite_master WHERE type='table' AND name='admin_requests'`);
    const adminTableExists = adminTableResult.length > 0 && adminTableResult[0].values.length > 0;
    
    if (!adminTableExists) {
      console.log('sql.worker.ts: Creating admin_requests table');
      db.run(`
        CREATE TABLE IF NOT EXISTS admin_requests (
          id TEXT PRIMARY KEY,
          residentId TEXT,
          residentName TEXT,
          email TEXT,
          phone TEXT,
          reason TEXT,
          status TEXT,
          reviewedBy TEXT,
          reviewNotes TEXT,
          createdAt TEXT,
          updatedAt TEXT
        )
      `);
      console.log('sql.worker.ts: admin_requests table created');
    } else {
      console.log('sql.worker.ts: admin_requests table already exists');
    }
  } catch (e: any) {
    console.warn('sql.worker.ts: Migration error for admin_requests:', e.message);
  }

  // Ensure suggestions table exists
  try {
    const suggestionsTableResult = db.exec(`SELECT name FROM sqlite_master WHERE type='table' AND name='suggestions'`);
    const suggestionsTableExists = suggestionsTableResult.length > 0 && suggestionsTableResult[0].values.length > 0;
    
    if (!suggestionsTableExists) {
      console.log('sql.worker.ts: Creating suggestions table');
      db.run(`
        CREATE TABLE IF NOT EXISTS suggestions (
          id TEXT PRIMARY KEY,
          type TEXT,
          name TEXT,
          email TEXT,
          phone TEXT,
          message TEXT,
          status TEXT,
          response TEXT,
          createdAt TEXT,
          updatedAt TEXT
        )
      `);
      console.log('sql.worker.ts: suggestions table created');
    } else {
      console.log('sql.worker.ts: suggestions table already exists');
    }
  } catch (e: any) {
    console.warn('sql.worker.ts: Migration error for suggestions:', e.message);
  }
}

async function ensureInit() {
  console.log('sql.worker.ts: ensureInit called');
  if (SQL && db) {
    console.log('sql.worker.ts: Already initialized');
    return;
  }
  const init = initSqlJs;
  if (typeof init !== 'function') {
    console.error('sql.worker.ts: initSqlJs is not a function. Check /public/sql-wasm.js');
    throw new Error('initSqlJs is not a function. Check /public/sql-wasm.js');
  }

  // Try to fetch the wasm from a few likely locations and pass the binary to initSqlJs
  const candidates = [
    '/sql-wasm.wasm',
    'https://cdn.jsdelivr.net/npm/sql.js@1.13.0/dist/sql-wasm.wasm',
  ];

  let wasmBinary = null;
  for (const url of candidates) {
    try {
      console.log('sql.worker.ts: Trying to fetch wasm from', url);
      const res = await fetch(url);
      if (res.ok) {
        wasmBinary = await res.arrayBuffer();
        console.log('sql.worker.ts: Successfully fetched wasm from', url);
        break;
      } else {
        console.warn('sql.worker.ts: wasm fetch failed', url, res.status);
      }
    } catch (err) {
      console.warn('sql.worker.ts: wasm fetch error', url, err && err.message ? err.message : err);
    }
  }

  if (wasmBinary) {
    SQL = await init({ wasmBinary });
    console.log('sql.worker.ts: SQL initialized with wasmBinary');
  } else {
    SQL = await init({
      locateFile: (file: string) => '/sql-wasm.wasm',
    });
    console.log('sql.worker.ts: SQL initialized with locateFile fallback');
  }

  db = new SQL.Database();
  console.log('sql.worker.ts: Database created');
  // Create schema if not exists
  db.run(`
    CREATE TABLE IF NOT EXISTS residents (
      id TEXT PRIMARY KEY,
      firstName TEXT NOT NULL,
      lastName TEXT NOT NULL,
      middleName TEXT,
      dateOfBirth TEXT,
      email TEXT,
      phone TEXT,
      address TEXT,
      gender TEXT,
      civilStatus TEXT,
      isPWD INTEGER DEFAULT 0,
      status TEXT,
      createdAt TEXT,
      updatedAt TEXT
    );
    CREATE TABLE IF NOT EXISTS officials (
      id TEXT PRIMARY KEY,
      firstName TEXT NOT NULL,
      lastName TEXT NOT NULL,
      position TEXT,
      email TEXT,
      phone TEXT,
      term TEXT,
      createdAt TEXT,
      updatedAt TEXT
    );
    CREATE TABLE IF NOT EXISTS documents (
      id TEXT PRIMARY KEY,
      type TEXT,
      residentId TEXT,
      issueDate TEXT,
      expiryDate TEXT,
      content TEXT,
      status TEXT,
      createdAt TEXT,
      updatedAt TEXT
    );
    CREATE TABLE IF NOT EXISTS blotter_records (
      id TEXT PRIMARY KEY,
      reporterName TEXT,
      reporterContact TEXT,
      incidentDate TEXT,
      incidentLocation TEXT,
      description TEXT,
      status TEXT,
      remarks TEXT,
      summonDate TEXT,
      summonTime TEXT,
      createdAt TEXT,
      updatedAt TEXT
    );
    CREATE TABLE IF NOT EXISTS activities (
      id TEXT PRIMARY KEY,
      type TEXT,
      description TEXT,
      userId TEXT,
      targetId TEXT,
      createdAt TEXT
    );
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      email TEXT UNIQUE,
      displayName TEXT,
      passwordHash TEXT,
      passwordSalt TEXT,
      isAdmin INTEGER DEFAULT 0,
      createdAt TEXT,
      updatedAt TEXT
    );
    CREATE TABLE IF NOT EXISTS admin_requests (
      id TEXT PRIMARY KEY,
      residentId TEXT,
      residentName TEXT,
      email TEXT,
      phone TEXT,
      reason TEXT,
      status TEXT,
      reviewedBy TEXT,
      reviewNotes TEXT,
      createdAt TEXT,
      updatedAt TEXT
    );
    CREATE TABLE IF NOT EXISTS suggestions (
      id TEXT PRIMARY KEY,
      type TEXT,
      name TEXT,
      email TEXT,
      phone TEXT,
      message TEXT,
      status TEXT,
      response TEXT,
      createdAt TEXT,
      updatedAt TEXT
    );
  `);

  // Ensure hard-coded admin account exists
  ensureAdminAccount();
  console.log('sql.worker.ts: Schema created');
  
  // Run migrations to ensure all tables exist
  runMigrations();
  
  // Add migration for missing columns in existing residents table
  try {
    const result = db.exec(`PRAGMA table_info(residents)`);
    const columns = result[0]?.values.map((row: any) => row[1]) || [];
    console.log('sql.worker.ts: Residents columns:', columns);
    
    if (!columns.includes('gender')) {
      console.log('sql.worker.ts: Adding gender column to residents');
      try {
        db.run(`ALTER TABLE residents ADD COLUMN gender TEXT`);
        console.log('sql.worker.ts: gender column added successfully');
      } catch (e: any) {
        console.log('sql.worker.ts: gender column - ', e.message);
      }
    }
    
    if (!columns.includes('civilStatus')) {
      console.log('sql.worker.ts: Adding civilStatus column to residents');
      try {
        db.run(`ALTER TABLE residents ADD COLUMN civilStatus TEXT`);
        console.log('sql.worker.ts: civilStatus column added successfully');
      } catch (e: any) {
        console.log('sql.worker.ts: civilStatus column - ', e.message);
      }
    }

    if (!columns.includes('isPWD')) {
      console.log('sql.worker.ts: Adding isPWD column to residents');
      try {
        db.run(`ALTER TABLE residents ADD COLUMN isPWD INTEGER DEFAULT 0`);
        console.log('sql.worker.ts: isPWD column added successfully');
      } catch (e: any) {
        console.log('sql.worker.ts: isPWD column - ', e.message);
      }
    }
    
    // Re-check columns after migration
    const result2 = db.exec(`PRAGMA table_info(residents)`);
    const columns2 = result2[0]?.values.map((row: any) => row[1]) || [];
    console.log('sql.worker.ts: Residents columns after migration:', columns2);
  } catch (err) {
    console.warn('sql.worker.ts: Migration check failed', err);
  }
}

function send(id: number, payload: any) {
  self.postMessage({ id, ...payload });
}

self.addEventListener('message', async (ev: MessageEvent) => {
  const msg = ev.data;
  const { id, type, sql, params, data } = msg;
  try {
    console.log('sql.worker.ts: Received message', type);
    if (type === 'init') {
      await ensureInit();
      send(id, { ok: true, result: true });
      return;
    }
    if (type === 'exec') {
      await ensureInit();
      db.run(sql, params || []);
      send(id, { ok: true, result: true });
      return;
    }
    if (type === 'query') {
      await ensureInit();
      const res = db.exec(sql, params || []);
      const out = [];
      if (res && res[0]) {
        const { columns, values } = res[0];
        for (const row of values) {
          const obj: any = {};
          for (let i = 0; i < columns.length; i++) obj[columns[i]] = row[i];
          out.push(obj);
        }
      }
      send(id, { ok: true, result: out });
      return;
    }
    if (type === 'save') {
      await ensureInit();
      const exported = db.export();
      send(id, { ok: true, result: exported });
      return;
    }
    if (type === 'load') {
      await ensureInit();
      db = new SQL.Database(new Uint8Array(data));

      // Ensure hard-coded admin account exists after loading DB
      ensureAdminAccount();

      // Apply migrations after loading from localStorage
      try {
        // Check if admin_requests table exists
        const adminTableResult = db.exec(`SELECT name FROM sqlite_master WHERE type='table' AND name='admin_requests'`);
        const adminTableExists = adminTableResult.length > 0 && adminTableResult[0].values.length > 0;
        
        if (!adminTableExists) {
          console.log('sql.worker.ts: Creating admin_requests table in loaded database');
          try {
            db.run(`
              CREATE TABLE IF NOT EXISTS admin_requests (
                id TEXT PRIMARY KEY,
                residentId TEXT,
                residentName TEXT,
                email TEXT,
                phone TEXT,
                reason TEXT,
                status TEXT,
                reviewedBy TEXT,
                reviewNotes TEXT,
                createdAt TEXT,
                updatedAt TEXT
              )
            `);
            console.log('sql.worker.ts: admin_requests table created successfully');
          } catch (e: any) {
            console.log('sql.worker.ts: admin_requests table creation error - ', e.message);
          }
        }
        
        // Check if suggestions table exists and create if missing
        const suggestionsTableResult = db.exec(`SELECT name FROM sqlite_master WHERE type='table' AND name='suggestions'`);
        const suggestionsTableExists = suggestionsTableResult.length > 0 && suggestionsTableResult[0].values.length > 0;
        
        if (!suggestionsTableExists) {
          console.log('sql.worker.ts: Creating suggestions table in loaded database');
          try {
            db.run(`
              CREATE TABLE IF NOT EXISTS suggestions (
                id TEXT PRIMARY KEY,
                type TEXT,
                name TEXT,
                email TEXT,
                phone TEXT,
                message TEXT,
                status TEXT,
                response TEXT,
                createdAt TEXT,
                updatedAt TEXT
              )
            `);
            console.log('sql.worker.ts: suggestions table created successfully');
          } catch (e: any) {
            console.log('sql.worker.ts: suggestions table creation error - ', e.message);
          }
        }
        
        // Migrate residents table columns
        const result = db.exec(`PRAGMA table_info(residents)`);
        const columns = result[0]?.values.map((row: any) => row[1]) || [];
        console.log('sql.worker.ts: Residents columns after load:', columns);
        
        if (!columns.includes('gender')) {
          console.log('sql.worker.ts: Adding gender column to loaded residents');
          try {
            db.run(`ALTER TABLE residents ADD COLUMN gender TEXT`);
            console.log('sql.worker.ts: gender column added to loaded database');
          } catch (e: any) {
            console.log('sql.worker.ts: gender column add - ', e.message);
          }
        }
        
        if (!columns.includes('civilStatus')) {
          console.log('sql.worker.ts: Adding civilStatus column to loaded residents');
          try {
            db.run(`ALTER TABLE residents ADD COLUMN civilStatus TEXT`);
            console.log('sql.worker.ts: civilStatus column added to loaded database');
          } catch (e: any) {
            console.log('sql.worker.ts: civilStatus column add - ', e.message);
          }
        }

        // Ensure users table exists on loaded database
        try {
          const usersTableResult = db.exec(`SELECT name FROM sqlite_master WHERE type='table' AND name='users'`);
          const usersTableExists = usersTableResult.length > 0 && usersTableResult[0].values.length > 0;
          if (!usersTableExists) {
            console.log('sql.worker.ts: Creating users table in loaded database');
            db.run(`
              CREATE TABLE IF NOT EXISTS users (
                id TEXT PRIMARY KEY,
                email TEXT UNIQUE,
                displayName TEXT,
                passwordHash TEXT,
                passwordSalt TEXT,
                isAdmin INTEGER DEFAULT 0,
                createdAt TEXT,
                updatedAt TEXT
              )
            `);
          }
        } catch (e: any) {
          console.log('sql.worker.ts: users table creation error - ', e.message);
        }
      } catch (err) {
        console.warn('sql.worker.ts: Migration after load failed', err);
      }
      
      send(id, { ok: true, result: true });
      return;
    }
    send(id, { ok: false, error: 'Unknown message type' });
  } catch (err) {
    const errorMsg = err && err.message ? err.message : String(err);
    console.error('sql.worker.ts: message handler error', errorMsg, err);
    send(id, { ok: false, error: errorMsg });
  }
});

self.addEventListener('error', (ev: ErrorEvent) => {
  try {
    const errorMsg = ev && ev.message ? ev.message : String(ev);
    console.error('sql.worker.ts: global error', errorMsg, ev);
    self.postMessage({ id: -1, ok: false, error: errorMsg });
  } catch (e) {}
});

self.addEventListener('unhandledrejection', (ev: PromiseRejectionEvent) => {
  try {
    const reason = (ev && ev.reason) || ev;
    const msg = reason?.message || String(reason) || 'Unknown error';
    console.error('sql.worker.ts: unhandled rejection', msg, reason);
    self.postMessage({ id: -1, ok: false, error: msg });
  } catch (e) {}
});
